import 'package:flutter_test/flutter_test.dart';
import 'package:fortia/features/progress/domain/overload_suggestion.dart';
import 'package:fortia/core/database/app_database.dart';

// Helper to create a mock WorkoutSet-like structure
// Since WorkoutSet is generated by Drift, we test the logic conceptually
void main() {
  group('OverloadCalculator', () {
    test('returns null for empty sessions', () {
      final result = OverloadCalculator.suggest(
        exerciseName: 'Supino',
        lastSessions: [],
        targetReps: 12,
      );
      expect(result, isNull);
    });

    // Note: Full integration tests require generated Drift classes
    // These will be tested via integration tests
  });
}
